# Generated by Django 3.2.10 on 2022-02-18 03:58

from django.db import migrations, models
import django.utils.timezone
import fileupload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=fileupload.models.getfilename, max_length=100, null=True)),
                ('file', models.FileField(upload_to=fileupload.models.upload_file_path)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('upload_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
